### ISSUE TITLE
Don't use [EnsureUTF16] (gone from Web IDL)

### ISSUE THREAD

**Issue by foolip** [w3c/FileAPI#9]
It is used in https://w3c.github.io/FileAPI/#file for the `fileName` argument in the constructor. It has however been removed from the Web IDL spec:
https://github.com/heycam/webidl/commit/e2cf800ef401578db8d1445d815dc13bc8899554

Perhaps USVString would work, that's what it already is in Gecko:
https://github.com/mozilla/gecko-dev/blob/9d30f59efd1f82cfa80633c43834b7f08a9c77e1/dom/webidl/File.webidl

**Comment by arunranga** [comment]
I think the warning here on USVString is, "when in doubt, use DOMString."

In general, for a file name, we don't strictly need Unicode scalars to operate on. So I'm wondering whether the right fix here is to simply revert to DOMString.

**Comment by annevk** [comment]
How would you then transmit that filename? Everything part of `File` needs to be serialized. DOMString cannot be serialized.

**Comment by arunranga** [comment]
>>How would you then transmit that filename? Everything part of File needs to be serialized. DOMString cannot be serialized.

Well, WebIDL does include an algorithm for converting a DOMString to a sequence of Unicode scalar values and is part of the DOMString definition, so we *can* serialize them after doing something like that. 

But if this bug is to replace [EnsureUTF16] with USVString as a type instead of DOMString, then maybe that's ok especially since it's in Gecko. 

Separately, the current check for illegal chars in fileName may be inadequate. Right now, we only replace "/" with ":" which may be wrong on some OS's. I wonder if we should do a more exhaustive check, sort of like this (scroll down): https://www.dropbox.com/help/145 and in general include more for fileName's definition.

**Comment by Ms2ger** [comment]
@mkruisselbrink could you replace `[EnsureUTF16] DOMString fileName,` by `USVString fileName,` please? It's not a normative change, just an update to match the syntax change in WebIDL.
